# Generated by Django 5.1.3 on 2025-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('popularity_score', models.FloatField()),
                ('weight', models.FloatField()),
                ('image_yellow', models.URLField()),
                ('image_rose', models.URLField()),
                ('image_white', models.URLField()),
            ],
        ),
    ]
